### PR TITLE
Update ReikaJVMParser.java

### PR DESCRIPTION
**Pull request by TroublePanic**
Line 87: strip everything but the version number first. should alleviate problems from rogue alphabetics.
ref:  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1255#c25426

### CODE REVIEW

**Comment by TroublePanic** [comment]
Or, i could use [Oracle's Java](http://ubuntu.itsprite.com/ubuntuhow-to-install-openjdk-8-on-14-04-lts/), which has a version number that isn't stupid.

**Comment by TomeWyrm** [comment]
It'll be included in the next release. He won't accept/push/pull/whatever the request precisely. But it will be included. (He's busy mucking with configs, and asked that I tell you)

**Comment by TroublePanic** [comment]
awesome

**Comment by ReikaKalseki** [comment]
Included.

**Pull request closed without merging**
