### PR TITLE
Move classes into packages matching java conventions

### PR DESCRIPTION
**Pull request by phase**
A source folder has been added. All the classes were moved into here and the packages were lowercased.

### CODE REVIEW

**Comment by ReikaKalseki** [comment]
Absolutely not.

**Comment by ReikaKalseki** [comment]
Absolutely not.

**Comment by phase** [comment]
This is normal Java convention. Package names are lowercased and put in the `src` folder. [Check my fork](https://github.com/phase/DragonAPI/tree/master/src/reika/dragonapi) to see the files, they're there.

**Comment by ReikaKalseki** [comment]
> This is normal Java convention.

I know. I also do not care.

**Comment by phase** [comment]
What if I want to use this in my Maven or Gradle project? I'd have to do this all myself. If your dev environment expects your code organized like _this_, you're doing Java wrong. Go? Maybe. Java? Absolutely not. If you're using Eclipse, your code is in a source folder. If you're using IntelliJ, your code is in a source folder. There's no way you could compile this code without putting it in two directories.

**Comment by ReikaKalseki** [comment]
Mine is not set up like that, and I am not willing to do so, as again:

> My way is cleaner, easier to work with, [and] more accurate

**Comment by phase** [comment]
How is this cleaner? You're deliberately keeping your code out of a folder that was invented for organization. And _accuracy_? I've got no idea how anyone could think that not following conventions is _accurate_.

**Comment by phase** [comment]
Thinking that you can break "rules" is fun, but this isn't a "rule". It is a "standard". If you want your code to be respected by anyone that knows what they're doing, you follow the standard. The fact that it has held up for so long should attest to how much it works.

**Comment by ReikaKalseki** [comment]
> How is this cleaner? 

Less (in fact, no) packages that serve as nothing but additional level of folder "just because". The same reason I frown on things like "com.java.src.mod.<actual code starts here>". This is also the reason I say it is easier to use. More clicking for the same functionality is worse in all cases, no exceptions.

> And accuracy? I've got no idea how anyone could think that not following conventions is accurate.

Because it is called "DragonAPI", not "dragonapi", my name is "Reika", not "reika", and they are called "TileEntit(y/ies)", "Worlds" and "Maps", not "tileentit(y/ies)", "worlds", and "maps". Also, they are names, and names get capitalized.

> If you want your code to be respected by anyone that knows what they're doing, you follow the standard.

If someone's approval hinges on following arcane, pointless, and actively detrimental restrictions *just because*, I can do without it.

You are [not the first to say this](https://www.reddit.com/r/feedthebeast/comments/2eoc01/why_are_there_so_many_badly_written_but_popular/). You will not be the last.

> The fact that it has held up for so long should attest to how much it works.

Because too many people blindly follow books and accept what their peers say as gospel. Again, unless you can prove a *practical* reason for doing it your way, you may as well be saying "never start a class name with a "K", because <programmer from 1970> wrote it in <600 page book>", "never eat eggs before cheese, because my grandmother said it was bad", or "if you like both fish and steak, you're some freak of nature because my shaman said so".

**Comment by phase** [comment]
> Maybe next time, if you actually have an argument, you can try asking it to my face.

Being hostile towards people for pointing out that _you are doing it wrong_ is not how you become a better programmer. Writing bad code is fine. Being a bad programmer is fine. Being a _stubborn_ programmer, that's where you fault yourself. Only _you_ can change yourself for the better. Yes, the methodology may be old. Yes, standards may not have any significant reason for existing, but this is how people write code. This is how _good programmers_ write _good code_. If you want to fight off everyone _trying to help you_, so be it.

**Comment by ReikaKalseki** [comment]
> Being hostile towards people for pointing out that you are doing it wrong

If, as in this case, I am not actually doing it, wrong, just differently, and they are hostile to begin with, then yes, it is justified.

> Being a stubborn programmer, that's where you fault yourself. 

If I were insisting on iterating over maps to do lookups or returning zero hashcodes, you would have a case. Not where it boils down to a stylistic change.

> Yes, standards may not have any significant reason for existing

And that right there is the problem.

> this is how people write code. 

And that mentality is the same reason there are people hacking each other apart halfway around the world, the reason that half of the planet's population struggles to be viewed as equals, the reason that large areas of the world are in total stagnation, and more. "This is how it is because it is". is *never* a valid justification. **Ever.**

**Comment by phase** [comment]
> they are hostile to begin with

It doesn't matter if you were first or they were, being "_hostile_" over Minecraft mods is ridiculous.

> they rant about variable names, { placement, and mod balance and design.

Luckily, I didn't have to read any of your code. I only moved the packages. I could tell from doing that the code wouldn't be much better. It's probably not following Java standards either.

> same reason there are people hacking each other apart halfway around the world

This is not politics, this is programming. Being a rebel in programming will get you nowhere. I, and many others, look at this and think, "he doesn't know Java." Looking at your repository structure, I see no indication that you have any Java experience outside a "Hello World" program. "_Going against the norm_" is not what programmers do in this context.

**Comment by ReikaKalseki** [comment]
> "he doesn't know Java."

Sure, that is how I write fifteen mods, some huge, all of which work fairly well and performantly, and which are popular within their target audiences. All without understanding the language.

> I see no indication that you have any Java experience outside a "Hello World" program.

If you mean prior education, you would be correct! Another point against me, I assume? Programming is only for the 'professions' who spent ten years in University doing nothing else?

**Comment by phase** [comment]
> All without understanding the language.
You may know how to write code that can compile, but you're not writing code that others want to read. This PR was to help that.

**Comment by ReikaKalseki** [comment]
I do not write code for leisure reading. I wrote code for the end result.

**Comment by Kolatra** [comment]
Oh no! A few people don't want to read the code because the package names aren't lowercase!

**Comment by phase** [comment]
> I wrote code for the end result.

Write better code and you may get a better result.

> people don't want to read the code because the package names aren't lowercase

The _majority_ of Java developers follow Java conventions. That's what makes them standards.

**Comment by ReikaKalseki** [comment]
> Write better code and you may get a better result.

Do you seriously expect me to believe that capitalization or folder structure affects how a program behaves?

**Comment by Kolatra** [comment]
I follow the conventions myself, some of them at least, I can still clearly read and understand Reika's code. It really doesn't look good that you're being a code justice warrior.

**Comment by phase** [comment]
> capitalization or folder structure affects how a program behaves

~~If you look closely, you can see that a capital R has a 17% chance of throwing a NPE.~~
Of course not. Obviously conventions don't affect how a program runs. Conventions help you write better code, which _will_ affect how a program runs.

> code justice warrior

Quite a clever name. Without its ties to radical feminism, I might have printed it out and taped it to the top of my monitor. Actually, I'm going to go down to BestBuy and grab a couple ink cartridges.

**Comment by ReikaKalseki** [comment]
> Conventions help you write better code, which will affect how a program runs.

Just no. For one, half of the conventions I see - hungarian notation and "never declare local variables unless you have to" are actively *bad* for the code, as they make it unreadable, difficult to write, or less performant. Others are contradictory, like "cache everything" and "never declare local variables". Yet others do nothing but add pointless verbosity, like "never ever have a public field". Most reek of "let's see if I can still program while following stupid rules", much like "now try to play Minecraft without jumping", or "see if you can get through Factorio without using belts".

On top of that, every bit of extra time I spend accommodating to arbitrary restrictions is time I cannot spend on something that actually matters.

**Comment by phase** [comment]
> accommodating to arbitrary restrictions

Clean package names, that follow the Java standard, are how people name packages. Being a rebel for the sake of it is ignorant. Being stubborn will not help you become a better developer.

**Comment by Kolatra** [comment]
Reika is not the only Java or even *mod* developer to have capitalized package names.

**Comment by phase** [comment]
~~Thank you, Sherlock. You sure solved the msyery1~~

```
ma·jor·i·ty
məˈjôrədē,məˈjärədē/
noun
1.
the greater number.
```

Yes, some people use capitalized packages.

**Comment by Kolatra** [comment]
So why do you care how Reika codes? It's his mod, and it works. That's all that should matter to you.

**Comment by phase** [comment]
I'm just going out of my way to right someone's wrongs. If they don't want to take my advice, they don't have to. I honestly couldn't care less how Reika codes. I just found a project on GitHub that looked like it needed some help.

> and it works

I do not care that it works. That is not the point of this PR, that is not the point of this discussion.

**Comment by Kolatra** [comment]
Someone's wrongs? You're completely missing the point of your argument. You are arguing that Reika is not following Java conventions, because *most* people do it a *different* way. This doesn't mean it's wrong. It's simply different.

**Comment by phase** [comment]
Different doesn't mean it's correct. 

Let's go over some things:

* [This is how you name Java packages](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).
* Reika is not doing this.
* I made a Pull Request on GitHub to fix it.
* It was declined.
* I argued that this is Java standard, and that following that standard is normal.
* Reika wants to be a rebel.

Unless I'm wrong, that seems to be the gist of what has happened, along with what my argument pertains to. Don't tell me I do not understand my argument when I am literally the one who made it.

**Comment by ReikaKalseki** [comment]
> Different doesn't mean it's correct. 

It also does not make it wrong, something you *really* are unwilling to accept or are genuinely unable to grasp.

**Comment by Kolatra** [comment]
Reika is not being a rebel. He has given reasons for why he does what he does, and you seem to be incapable of understanding that and can't accept no as an answer.

**Comment by ReikaKalseki** [comment]
> He has given reasons for why he does what he does

I want to elaborate on that. I have reasons on why your system is *demonstrably worse* from a practical perspective, and your only justification for using it is "because some guy said so".

**Comment by coolsquid** [comment]
So... You're making a PR that would break every one of Reika's mods and every other mod that interacts with DragonAPI, _because you don't like the package names_. And then you go on ranting about why Reika is wrong, the sole argument being that "it isn't right", even though there are no official rules on the subject... Wow.

**Comment by phase** [comment]
> genuinely unable to grasp

> incapable of understanding

I am fully aware of the reasons Reika wants to program like this. I am saying it is bad. I have my opinion, he has his.

> your only justification for using it is "because some guy said so"

picture of someone riding their bike backwards

There is a reason people don't ride their bikes backwards. Is it harder? Yes. It is unsafe? Yes. But why didn't we start out riding our bikes backwards? Because the man who invented it told us, "Hey, you want to ride it this way. It's a lot easier this way." Now, in the grand scheme of things, no one gives a fuck about what you name your packages. I'm just passing information along from the guy who started it.

> are no official rules on the subject

Those are the wonders of programming. Anyone can do it however they like and it will still compile!

My original intention was to inform a developer who may not know of Java standards, but they obviously  wish to go against them.

**Comment by Kolatra** [comment]
You realize that your last comment completely invalidates your whole argument right? Opinions are not right or wrong, they are your own, so neither you or Reika are wrong. You're completely contradicting yourself.

**Comment by ReikaKalseki** [comment]
> There is a reason people don't ride their bikes backwards. Is it harder? Yes. It is unsafe? Yes. But why didn't we start out riding our bikes backwards?

I assume you missed the point where riding bikes backwards poses practical issues, where your whole standard does not?

**Comment by phase** [comment]
> I assume you missed the point where riding bikes backwards poses practical issues, where your whole standard does not?

That is obvious. That is _so_ obvious. OF COURSE THERE'S A DIFFERENCE! IT'S THE PRINCIPLE OF IT!

That's why I added

> Now, in the grand scheme of things

but I guess that didn't get the point across that **there is a difference between Java packages and bikes**.

> invalidates your whole argument right

~~wowthat'scrazyhowdidthisoccur~~

Saying, "you're contradicting yourself," over and over isn't adding to the conversation.

---

What
if
I
formatted
my
text
like
this?

Annoying,
right?

This is how I feel with your packages. Obviously, you're not going to change them. I just wanted to tell you that they aren't following Java conventions.

**Comment by Kolatra** [comment]
Well, I'm telling you that you're contradicting yourself, because *you are*...

**Comment by ReikaKalseki** [comment]
> you're not going to change them. I just wanted to tell you that they aren't following Java conventions.
> My original intention was to inform a developer who may not know of Java standards

If this were true, you would not have continued to reply after being rejected, and would not have acted like my refusal to do it was a personal assault.

**Comment by phase** [comment]
> personal assault

I apologize if my response made it sound like I was offended. I'm not.

> If this were true

It _was_ true, but now I'm arguing that Java conventions are better than rebelling against them for no reason. Oh wait, because "names get capitalized." Not in packages. Class names? Totally. Variables? Nope. Fields? Nope. Parameters? Nope. Packages? Nope.

**Comment by Kolatra** [comment]
I have stated that Reika has reasons for doing what he does, he is not rebelling for no reason, and he has expanded on my point.

**Comment by phase** [comment]
> I have stated

Yes, you have. :tada:

**Comment by Kolatra** [comment]
And you seem to be completely ignoring it because it's not what you want to see.

**Comment by phase** [comment]
I'm not ignoring his reasons at all. I'm saying they're bad.

**Comment by Kolatra** [comment]
You keep saying that he's "being rebellious for no reason at all" even though we have proven that wrong. Yes, you're ignoring it.

**Comment by phase** [comment]
I don't find his ideas to be valid reasons. Quit digging through my linguistics.

**Comment by Kolatra** [comment]
They're not valid *in your opinion*, thank you for expressing your opinion, but Reika simply is not going to break his mods and other mods that use his mods because somebody doesn't like the way he names his packages. In the end, it seriously should not be an issue to you. It's not your mod.

**Comment by ReikaKalseki** [comment]
> I don't find his ideas to be valid reasons.

So "because it is" is supposed to override "this is easier for me"?

**Comment by phase** [comment]
> it seriously should not be an issue to you. It's not your mod.

No shit. You keep reiterating this, and I'm 100% in agreement with you. Reika can do whatever he wants to. It doesn't matter to me.

> easier for me

I don't know how hitting the shift key is easier than not, but okay.

**Comment by Kolatra** [comment]
It doesn't matter to you? Why are we even having this argument then?

**Comment by phase** [comment]
I want it to change, but if it doesn't, I don't care. It's not going to affect me either way. I'm saying following Java conventions is better than doing your own thing because of minuscule reasons.

**Comment by Kolatra** [comment]
I think it's already been made pretty clear that it's not gonna change. Sorry.

**Comment by phase** [comment]
Really? I was pretty sure I had a chance at changing it! If I sit here for another couple hours and hammer away at my keyboard, surely he'll change his opinion.

Oh wait, unbeknownst to you, I actually have some intelligence. No shit this isn't going through. It was obvious when this PR was closed.

> Absolutely not

**Comment by Kolatra** [comment]
So much salt you could build a castle.

**Comment by phase** [comment]
That sums up your comments quite well. You've added _nothing_ to this discussion.

**Comment by ReikaKalseki** [comment]
> I don't know how hitting the shift key is easier than not, but okay.

More readable, and less folders equal less clicks. Done. Any more questions, or just more pointless bawling?

**Comment by Kolatra** [comment]
It's not even a discussion at this point. It's pointless shitposting.

**Comment by phase** [comment]
> More readable

Learn to read.

> It's pointless shitposting.

Don't you have some YouTube video to comment on?

---

That's it for me. l8r g8rs.

**Comment by ConnorHartley** [comment]
I ran out of popcorn.

**Comment by curz46** [comment]
Uh, there's actually good reason for not capitalising folder/package names, using the `me.author.projectname` convention and placing it in the source folder.

1. Leaving package names lowercase means that they look very different from ClassNames. It's very easy to know that `com.authorwebsite.name.somepackage.ClassName`, is in the package `com.authorwebsite.name.somepackage` rather than it being a subclass of `PackageName`, or even `Name` too, or even `AuthorWebsite'. It makes it easier to work with and to understand, avoiding confusion.
2. Using that specific package namespace means that projects are less likely to have class conflicts. In fact, they barely ever do. If someone makes a package called 'Objects', which you might have, and uses a class you might have, then what classes will know which one your classes or their classes want to import? However unlikely it is that this will happen, it makes this project able to scale so that people can depend and use it safely where without this change, it might be likely to happen. The argument that nobody else uses this kind of style so there'll be no conflicts is true, but I just find that funny rather than a valid reason to keep it.
3. Placing it in the `src` folder is just standard, for one. People will expect, in a Java project, to find the source code in the 'src' folder. And so will everyone else's editors. You've put this project publicly on GitHub, I assume, for contribution, and yet you're not willing to make it easier for developers to contribute? They will have to not only get used to it not being in the `src` folder, but configure their editors to call it source code. This is just difficult. The first point there is massive, as they probably won't even bother, which means no-one will want to contribute.

It's just a suggestion, obviously. This project is on GitHub, as I've mentioned, and GitHub is a collaboration platform. We're collaborating by trying to improve the development experience for the average developer. It really seems to me that you just don't want to do it, rather than find that your decisions are well supported with valid arguments. And that's fine, I guess. But if not, please consider my arguments. :)

Thanks.

**Comment by ConnorHartley** [comment]
I agree with @curz46 to the extent of wanting to know why you have made it like this and the point of putting it on GitHub like this? (Trying to ask as nice as possible)

**Comment by ReikaKalseki** [comment]
> Leaving package names lowercase means that they look very different from ClassNames

I have heard this before, and my response now is the same as always: Packages are just glorified folders, while classes are actual files. Any programmer - who are the only ones who have any business reading the source, let alone commenting on it - can tell that difference essentially instantly, with or without names. This holds for internal classes too, which are delimited with a '$'.

> Using that specific package namespace means that projects are less likely to have class conflicts. In fact, they barely ever do.

Four and a half years, over a million lines of code in 20K classes, and still not one conflict. Any additional benefit is superfluous.

> Placing it in the src folder is just standard

See my above replies regarding anything being 'standard'.

> People will expect, in a Java project, to find the source code in the 'src' folder.

Perhaps, but unless you want to claim that they, upon noticing its nonexistence, either leave in disgust or are unable to grasp its absence, this is not worth doing anything about.

> You've put this project publicly on GitHub, I assume, for contribution, and yet you're not willing to make it easier for developers to contribute?

Your assumption is in fact incorrect. My code is on GitHub for two purposes: Primarily as a glorified dropbox - the real variant of which has become increasingly difficult to use over the years - and secondarily so that those who wish to do so can use it to write documentation or interface with it (i.e. intermod compatibility). Neither require setting it up in a dev environment, and even if one did want to do so, the usual method involves dropping the precompiled jars into the libraries, whereupon class structure is irrelevant. Also, there have been a few people who *have* set them up in Eclipse and for whom the structure of the classpath was not an obstacle (72 dependencies, on the other hand...).

In actual fact, due to other concerns - [detailed on another one of my repositories](https://github.com/ReikaKalseki/RotaryCraft/blob/master/README.md) - I do not accept outside contributions at all, at least directly.


Again, I have heard all of these arguments dozens of times from dozens of people, and as far as I am concerned, they are either outright false, true but irrelevant, or such minor points as to be completely eclipsed by the practical reasons for which I use my current setup.

**Comment by ConnorHartley** [comment]
Would be nice if you clarified this in the README to prevent future arguments like this.

**Comment by Kolatra** [comment]
This kind of argument is so rare it's not really needed in my opinion.

**Comment by ConnorHartley** [comment]
Fair enough. xD Phase is just... one of those people.

**Comment by ReikaKalseki** [comment]
Most of the time, it does not manifest as an argument, but someone randomly mouthing off somewhere about how stupid I am.

**Comment by ConnorHartley** [comment]
Yeah, it escalated too far, but I was just saying for people who are generally confused like I.

**Comment by ReikaKalseki** [comment]
You appear to come from outside the MC community, judging from your repositories; to those inside the MC community, especially among the developers or those who interact with them, my stances are much more well-known.

**Comment by ConnorHartley** [comment]
Fair enough.

**Comment by phase** [comment]
> can tell that difference essentially instantly

`Reika.Base.SilkBlock` could be a number of things

* An object named `SilkBlock` inside an object named `Base` inside a class named `Reika`.

  ```java
  public class BlockRegistry {
      public Block SilkBlock;
  }

  public class Reika {
      public BlockRegistry Base;
  }
  ```

* A static class named `SilkBlock` inside a class named `Base` inside a package named `Reika`.

  ```java
  package Reika;

  public class Base {
      public static class SilkBlock extends Block {
      }
  }
  ```

* A field named `SilkBlock` inside a static class named `Base` inside a class named `Reika`

  ```java
  public class Reika {
      public static class Base {
          public static Block SilkBlock;
      }
  }
  ```

I have no way of telling _just by looking_ what `Reika.Base.SilkBlock` is. Obviously, I can look at the other packages in the repository and realize the package names are capitalized, but it still isn't as intuitive.

&nbsp;

`com.google.gson.Gson`

Since this is following the standard, I know instantly that the package is `com.google.gson` and the class is `Gson`. I don't need to look at the project structure. I don't need to open the source at all.

&nbsp;

I think "less clicks = easier" is not enough to warrant a whole new project structure. My IDE sure as hell won't automatically find the sources, nor will any other Java IDE.

> there have been a few people who _have_ set them up

There shouldn't be any reason that this is difficult, or even a question you have to ask. If your project was a Maven or Gradle project, _not_ being able to import it wouldn't be a question. If the code was in a source folder, every Java IDE would recognize it without thinking.

> forcing me to roll back 3-6 months worth of commits

This is a lack of git experience. Your commit messages also reflect this. Instead of hitting the merge button, you could have asked the pull requester to rebase their changes to the latest commit. The you merge, pull, and your code is fine.

**Comment by ReikaKalseki** [comment]
> Reika.Base.SilkBlock could be a number of things....

Considering I do not name fields that way, no.

> I have no way of telling, just by looking, what Reika.Base.SilkBlock is




> I think "less clicks = easier" is not enough to warrant a whole new project structure.

It is when you have motor control issues and each click takes roughly three attempts and five to ten seconds.

> This is a lack of git experience. Your commit messages also reflect this. Instead of hitting the merge button, you could have asked the pull requester to rebase their changes to the latest commit. The you merge, pull, and your code is fine.

GitHub's PR system enthusiastically told me that all I needed to do was click "merge", and everything else would happen automatically. I will never again trust it.

> That's why you read the code before you merge. If you don't understand something, ask!

You clearly skipped or are neglecting the part where I said that no amount of explanation can help someone understand code as well as the original author. If anyone should know this, it would be you, given how your entire life seems to revolve around code and its design (to the exclusion of all else).

**Comment by phase** [comment]
If I see `Reika.Base.SilkBlock` _in code_, I can't tell what it is without context clues. Standards give me the tools I need to determine what something is by assuming it is conforming to the standard. If I assume everyone is naming their packages according to the standard, then I can tell which part of a piece of code is the package without thinking about it.

> I will never again trust it.

The new squash feature is okay. I still prefer the command line.

> no amount of explanation

You may not understand it in the aame way as the original author, but you'll your own perspective of it.

> entire life seems to revolve around code 

My life also includes starting Internet arguments over that code.

**Comment by MaPePeR** [comment]
@phase You forgot to add the src folder to the commit, essentially removing the files from the repository. Revert this and use `git mv` instead of normal operating system file movement to keep history on files. 

Also there is at least one package name/class name conflict in the screenshots: Maps is a class of guava and TileEntity, Collections and Recipe are also good candidates ;)

**Comment by phase** [comment]
https://github.com/phase/DragonAPI/tree/master/src/reika/dragonapi

The commits are so poorly made I don't think having `Update 836` is going to help.

**Comment by ReikaKalseki** [comment]
@phase may be somewhat gratified to note that a couple months ago I ran across - eleven years into using Java - my first case where package capitalization actually matters. However even here it was not a "true" functional impact, as it was deliberately forced (ie something specifically and artificially imposed this requirement).

More specifically, when developing [My Satisfactory Calculator](https://github.com/ReikaKalseki/Satisfactory-Planner/tree/master), it turned out SceneBuilder will refuse to look in capitalized packages for custom JavaFX components, thus preventing one from using them (they still work fine in JavaFX itself, just cannot be added to the FXML via the SceneBuilder UI). Hence the reason for the - **extremely ugly** - random lowercase `fxexpansions` package that is part of the project.

Overall, I would consider eleven years of development before encountering a case where case (hah) mattered, especially when said case was contrived rather than natural, as a pretty strong exoneration of my original point.

And yes my MC mods still use capitalized packages.

And for bonus points: Have a look at my C# code ([example 1](https://github.com/ReikaKalseki/SeaToSea/blob/main/CrashZoneSanctuaryBiome.cs), [example 2](https://github.com/ReikaKalseki/FortressCore/blob/main/RecipeUtil.cs)); it is - *gasp!* - using Java-style lowerCamelCase! Again for readability reasons I might add, since C# UpperCamelCase is *massively* bad for confusing types and their members.

**Pull request closed without merging**
